### ISSUE TITLE
404 & 500

### ISSUE THREAD

**Issue by t1gor** [Visithor/visithor#14]
What would be the correct config for checking 404 and 500 response codes? 

I am trying to get 404 or 500 in my config:

``` yml
defaults:
    http_codes: [200, 302]
    options:
        verb: GET

urls:
    - [http://example.com/404-url, 404]
    - [http://example.com/500-url, 500]
```

But it somehow returns 400 code... Did I miss something?
