### ISSUE TITLE
Create profiles

### ISSUE THREAD

**Issue by mmoreram** [Visithor/visithor#5]
Each profile will have a set of options.

``` yaml
profiles:
    admin:
        role: ROLE_ADMIN
        firewall: firewall_admin
urls:
    - [my_admin_route, 200, {'profile': admin}]
```

Each time an url has defined a profile, all this profile content will be appended :)
